### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by htkcodes** [koralesky/binance-pump-detecor#2]
Is this project finished?

**Comment by koralesky** [comment]
Well, the functionality of watching market is working. I forgot to mention, that You need to add .env file with APIKEY and SECRETKEY with values from Your binance API, in order to make it work. Then runing python3 binancePump.py will make it run.
There is an issue with sending info to telegram, that I'm about to fix in a free time.

**Comment by htkcodes** [comment]
yea read the code a bit, telegram is working for me, i used json instead of .env
